개요, 콘솔 가이드 추가
TOAST-DOCS/Compute-Instance-Template pull request #1
Opened 2021-07-09 07:30 UTC by arzhna

2021-07-14 01:49 UTC, 5bpa requested changes

2021-07-14 01:49 UTC, 5bpa commented on ko/overview.md
> +인스턴스 템플릿(Instance Template) 서비스는 자주 사용하는 인스턴스 구성 요소 정보를 미리 정의해 보관하는 서비스입니다. 미리 정의한 인스턴스 템플릿을 이용해 빠르게 동일한 사양의 인스턴스를 생성하거나, 오토스케일을 사용하기 위한 스케일링 그룹 생성에 사용할 수 있습니다.
* 미리 정의한 인스턴스 템플릿을 이용해 ~~빠르게~~ 동일한 사양의 인스턴스를 "빠르게" 생성
* 사용할 수 있습니다. -> 사용자 가이드에서는 "사용합니다" 로도 많이 쓰는 듯 합니다.

2021-07-14 01:49 UTC, 5bpa commented on ko/overview.md
> +인스턴스 템플릿(Instance Template) 서비스는 자주 사용하는 인스턴스 구성 요소 정보를 미리 정의해 보관하는 서비스입니다. 미리 정의한 인스턴스 템플릿을 이용해 빠르게 동일한 사양의 인스턴스를 생성하거나, 오토스케일을 사용하기 위한 스케일링 그룹 생성에 사용할 수 있습니다.
* 오토스케일을 사용하기 위한 스케일링 그룹을 만들 때  -> 생성이 반복되어서 만든다로 하나 바꿔봅니다.

2021-07-14 01:49 UTC, 5bpa commented on ko/console-guide.md
> +    <td>생성될 인스턴스에 추가적으로 할당할 디스크의 이름, 타입, 크기를 설정 <br>크기는 10 ~ 2000GB 내의 값만 허용</td>
크기 제한에 대한 내용은 빼면 어떨까 합니다. 
이 값이 생각보다 자주 변하는 것 같거든요. 
이미 blockstorage 에 있는 내용은 outdated...
![image](https://user-images.githubusercontent.com/5210068/125547234-26b0b147-c9c5-482b-93c4-f2f9fe6b8b40.png)

2021-07-14 01:49 UTC, 5bpa commented on ko/console-guide.md
> +    <td>생성될 인스턴스에 추가적으로 할당할 디스크의 이름, 타입, 크기를 설정 <br>크기는 10 ~ 2000GB 내의 값만 허용</td>
여기도... ㅋㅋㅋ 이건 다른 분들께 수정 요청하겠습니다.
![image](https://user-images.githubusercontent.com/5210068/125547320-073fe5cf-82e6-4f74-9bd9-a0623eeac9ee.png)

2021-07-14 01:49 UTC, 5bpa commented on ko/console-guide.md
> +    <td>생성할 인스턴스에 연결할 네트워크. <br>최대 4개까지 연결 가능하며, 연결 순서가 중요. <br>첫 번째 네트워크가 기본 게이트웨이 주소로 설정됨</td>
최대 4개 이야기는 빼는게 어떨까 합니다. 
"여러 개의 네트워크를 설정할 수 있으나, 첫 번째 네트워크가 기본 ..."

2021-07-14 01:49 UTC, 5bpa commented on ko/console-guide.md
> +    <td>인스턴스 템플릿의 설명. 영자 기준으로 최대 255자.</td>
아래에서 '영문'으로 썼으니, 여기도 '영문'으로 바꾸는게 어떨까요?

2021-07-14 02:12 UTC, arzhna commented on ko/console-guide.md
> +    <td>인스턴스 템플릿의 설명. 영자 기준으로 최대 255자.</td>
좀 더 명확하게 `영문자`로 통일할게요.

2021-07-14 03:06 UTC, jhjang04 commented on ko/overview.md
> +인스턴스 템플릿(Instance Template) 서비스는 자주 사용하는 인스턴스 구성 요소 정보를 미리 정의해 보관하는 서비스입니다. 미리 정의한 인스턴스 템플릿을 이용해 빠르게 동일한 사양의 인스턴스를 생성하거나, 오토스케일을 사용하기 위한 스케일링 그룹 생성에 사용할 수 있습니다.
저는 빠르게보단 편리하게가 좀더 괜찮을지 싶습니다.

2021-07-14 03:12 UTC, jhjang04 commented on ko/console-guide.md
> +    <td>생성될 인스턴스에서 부팅 직후 실행할 스크립트<br> 영문자 기준 최대 65535자</td>
base64 인코딩 기준같습니다.
확인해보니 다행히 api 가이드에는 잘 명시되어있네요..ㅎㅎ;
콘솔가이드에선 별다른른 길이제한을 명시하진 않고있습니다.
![image](https://user-images.githubusercontent.com/22493143/125555039-79e83652-06b7-4a5f-bd10-34c37e6f8dd6.png)

2021-07-14 03:23 UTC, arzhna commented on ko/console-guide.md
> +    <td>생성될 인스턴스에서 부팅 직후 실행할 스크립트<br> 영문자 기준 최대 65535자</td>
인스턴스 템플릿의 예약 스크립트는 인코딩을 하지 않고, 인스턴스를 생성할 때 콘솔에서 인코딩해서 넣어줍니다. 
글자수 제한에 대한 내용은 뺄게요.

2021-07-14 03:24 UTC, arzhna commented on ko/overview.md
> +인스턴스 템플릿(Instance Template) 서비스는 자주 사용하는 인스턴스 구성 요소 정보를 미리 정의해 보관하는 서비스입니다. 미리 정의한 인스턴스 템플릿을 이용해 빠르게 동일한 사양의 인스턴스를 생성하거나, 오토스케일을 사용하기 위한 스케일링 그룹 생성에 사용할 수 있습니다.
3배 빠르 느낌보다는 `편리하게`나 `간편하게`가 더 좋겠네요.
간소화하는 기능이니 `간편하게`로 수정합니다.

2021-07-14 05:03 UTC, 5bpa approved these changes
:+1:

2021-07-22 04:48 UTC, youngkyungyu commented on ko/overview.md
> +* **가용성 영역**: 인스턴스가 만들어질 물리적인 위치
의견 드립니다. 메이저 이슈는 아니고 문서 구조를 조금 수정해야 해서 다음 배포 때 반영하셔도 좋지 않을까 합니다. ^^

-  같은 항목을 설명할 때 개요와 콘솔 가이드 설명이 조금씩 다른데요.
개요에서는 간단하게 용어 정의(설명), 가이드에서는 더 자세한 세부 사항까지 설명하는 것이 아니라면,
용어 정의는 개요에서만 하고 다른 페이지에서는 개요의 용어 정의 부분으로 이동할 수 있게 링크를 제공하면 좋겠습니다.

- 운영체제, OS 혼용 => 하나로 통일

2021-07-22 04:51 UTC, arzhna commented on ko/overview.md
> +* **가용성 영역**: 인스턴스가 만들어질 물리적인 위치
고맙습니다. 
이번달은 운영체제, OS 혼용만 수정해서 배포하겠습니다.

2021-07-22 04:54 UTC, merged